name = "email_monitoring"
compatibility_date = "2026-08-10"
account_id = "5b6797aa57ca0f90cef50399ebbdda59"
workers_dev = false
zone_id = "58779ba4346f0bbfedba0574f3bf0598"

# Entry point for the Worker
main = "src/index.ts"

[[d1_databases]]
binding = "SERVICES_EMAIL"
database_name = "services_mail"
database_id = "5269c612-421e-4d93-bfa2-ec69040123c5"

# Routes: configure Email Routing to forward to this worker endpoint.
# Example route (adjust to your DNS / Email Routing settings):
routes = ["services.lumaris.fr.eu.org/*"]
